services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=josephperson
      - POSTGRES_PASSWORD=0908
      - POSTGRES_DB=meschane_db
    ports:
      - 5432:5432
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data: