services:
  postgres:
    image: postgres:latest
    container_name: postgres-container
    environment:
      - POSTGRES_USER=meschane_user
      - POSTGRES_PASSWORD=meschane_password
      - POSTGRES_DB=meschane_db
    ports:
      - 5432:5432
    volumes:
      - db-data:/var/lib/postgresql

volumes:
  db-data:
